### ISSUE TITLE
README needs a note regarding g3n engine version

### ISSUE THREAD

**Issue by Juuliuus** [g3n/g3nd#41]
Hi,

First let me say this demo has completely blown me away, sooooo cool. (Kubuntu 20.04). Am I out of the loop? Because it seems to me there should be some serious buzz about the capabilities of g3n.

tldr; people need to know that they must install g3n v0.1.0 also. I had installed g3n v0.2.0 only at first and g3nd would not build/install.

I did not, at this time want to clone g3n or g3nd, so I used go get instead (I'm on go 1.18) for both.

Building g3nd produced these messages:
...
github.com/g3n/g3nd imports
	github.com/g3n/g3nd/app imports
	github.com/g3n/engine/camera/control: cannot find module providing package github.com/g3n/engine/camera/control
github.com/g3n/g3nd imports
	github.com/g3n/g3nd/app imports
	github.com/g3n/engine/util/application: cannot find module providing package github.com/g3n/engine/util/application

my solution was simply to:
go get github.com/g3n/engine@v0.1.0

then all is well.

**Comment by danaugrs** [comment]
Hey, thanks for the kind words!
I suspect the issue is we need to bump g3nd's version up.
If you clone the `g3nd` repo and then run `go build` does it work?

**Comment by Juuliuus** [comment]
Hi,

No I took a zip and added pieces from g3nd a bit at a time, figuring out what was needed, and added it to a testing program of mine, that paralleled g3nd.

I'm quite sure it will =not= build on g3n v0.2, there are too many issues.

But that is not to say there are too many problems. It is mostly, of course, that func's have migrated here and there. I think it would be great if g3nd was upgraded. I could work on since I have some experience porting it. But there are areas where I am unsure of what to do. That's why I added it piece by piece to my testing program.

I used the same g3n pull  you did (from the go.mod) when you re-wrote gokoban (thanks for that work, looking at that clued me in to getting my program to work at all). So an updated g3nd would also help many others.

What is the status for g3n v0.2++?

**Comment by Juuliuus** [comment]
I was delayed with another project but finally got around to your suggestion, forked and tested.

You are right.

Simply change the go mod to require g3n v0.2.0 (optionally the go version from 1.13)

Then go mod tidy

go run .

And everything works!

I was fooled by lines like the following when I was playing with the code locally:
mat := material.NewPhong(&math32.Color{1,0,0})

NewPhong, as an example, was an error.

These references are out and/or commented in the master code base, so I, somehow, had the wrong code. <sigh>. It was actually, though, a great learning experience.
